Introduce the Flower Enhancement Proposal process
adap/flower pull request #1122
Opened 2022-03-11 08:17 UTC by nfnt

#### What does this implement/fix? Explain your changes.

To document motivations and decisions for larger changes or features to Flower, an Enhancement Proposal process is proposed. This process is heavily influenced by similar processes in the Python language (https://peps.python.org) as well as in Kubernetes (https://git.k8s.io/enhancements/keps).
The goal of this process is to provide insight and transparency on upcoming features that might change how users or developers have to interact with Flower. By storing proposals as part of Flower's repository, the community has an easy and accessible way to understand and influence these important changes to Flower.

#### Any other comments?

This is very similar in style to the [Kubernetes Enhancement Proposal Process](https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/0000-kep-process/README.md). That process has been slightly simplified, as some parts only made sense in a project as large as Kubernetes.

2022-03-25 14:16 UTC, danieljanes commented on proposals/0001-20220311-flower-enhancement-proposals.md
> +For small changes and additions, going through the Enhancement Proposal process would be time-consuming and unnecessary. This, e.g., includes adding new Federated Learning algorithms, as these only a
```suggestion
For small changes and additions, going through the Enhancement Proposal process would be time-consuming and unnecessary. This includes, for example, adding new Federated Learning algorithms, as these only add features without changing how Flower works or is used.
```

2022-03-25 14:21 UTC, danieljanes commented on proposals/0001-20220311-flower-enhancement-proposals.md
> +  A list of other proposals that are releavent to this one.
```suggestion
  A list of other proposals that are relevant to this one.
```

2022-03-25 14:22 UTC, danieljanes commented on proposals/0001-20220311-flower-enhancement-proposals.md
> +The idea forming the enhancement should already have been discussed or pitched in the comminuty. As such, it needs a champion, usually the author, who shepherds the proposal. This person also has to
```suggestion
The idea forming the enhancement should already have been discussed or pitched in the comminuty. As such, it needs a champion, usually the author, who shepherds the proposal. This person also has to find committers to Flower willing to review the proposal.
```

2022-03-25 14:28 UTC, danieljanes commented on proposals/0001-20220311-flower-enhancement-proposals.md
> +title: Flower Enhancement Proposals
Flower Enhancements Design?
Flower Enhancements Doc?

2022-03-29 08:11 UTC, orlandohohmeier commented on proposals/0001-20220311-flower-enhancement-proposals.md
> +title: Flower Enhancement Proposals
I like "Flower Enhancement Doc"

2022-03-29 08:58 UTC, orlandohohmeier commented
@danieljanes addressed your comments and adjust the name as suggested. Please have another look.

2022-04-01 18:46 UTC, danieljanes commented on enhancements/0001-20220311-flower-enhancement-doc.md
> +  - [Github Issues](#github-issues)
```suggestion
  - [GitHub Issues](#github-issues)
```

2022-04-01 18:46 UTC, danieljanes commented on enhancements/0001-20220311-flower-enhancement-doc.md
> +For far-fetching changes or features proposed to Flower, an abstraction beyond a single Github issue or pull request is required in order to understand and communicate upcoming changes to the project
```suggestion
For far-fetching changes or features proposed to Flower, an abstraction beyond a single GitHub issue or pull request is required in order to understand and communicate upcoming changes to the project.
```

2022-04-01 18:46 UTC, danieljanes commented on enhancements/0001-20220311-flower-enhancement-doc.md
> +  A list of authors of the proposal. This is simply the Github ID.
```suggestion
  A list of authors of the proposal. This is simply the GitHub ID.
```

2022-04-01 18:49 UTC, danieljanes requested changes

2022-04-01 18:49 UTC, danieljanes commented on enhancements/0001-20220311-flower-enhancement-doc.md
> +The purpose of this process is to reduce the amount of "tribal knowledge" in our community. By moving decisions from Slack threads, video calls and hallway conversations into a well tracked artifact,
```suggestion
The purpose of this process is to reduce the amount of "tribal knowledge" in our community. By moving decisions from Slack threads, video calls, and hallway conversations into a well tracked artifact, this process aims to enhance communication and discoverability.
```

2022-04-04 12:55 UTC, tanertopal approved these changes

2022-04-04 17:21 UTC, danieljanes approved these changes

2022-04-04 17:24 UTC, danieljanes commented
@nfnt auto-merge is enabled, it'll automatically be merged once you update the branch with the latest changed from `main`

2022-04-05 14:31 UTC, danieljanes approved these changes

2022-04-06 11:37 UTC, merged