Let simulation start server with custom ClientManager
adap/flower pull request #1171
Opened 2022-04-04 10:14 UTC by negedng

#### Reference Issues/PRs
Can't start simulation with custom ClientManager.

#### What does this implement/fix? Explain your changes.
Adding extra parameters to default server initialization and simulation start to let users add a custom ClientManager instead of always using the SimpleClientManager.

#### Any other comments?

2022-04-04 10:30 UTC, tanertopal commented
@negedng thank you for the PR! Could you additionally prepare a changelog entry?

@danieljanes this looks good to me. I don't see any downsides of passing a custom client manager. Wdyt?

2022-04-04 11:08 UTC, negedng commented
@tanertopal I'm not sure what do you mean by adding a changelog entry. I updated the `doc/source/changelog.rst`, I hope it is the right way.

Also, one of the tests showed a formatting issue that I changed. I hope it is better now!

2022-04-04 17:08 UTC, danieljanes requested changes

2022-04-04 17:08 UTC, danieljanes commented on src/py/flwr/simulation/app.py
> +        If no strategy is provided, then `start_server` will use
```suggestion
        If no implementation is provided, then `start_simulation` will use
```

2022-04-04 17:08 UTC, danieljanes commented on src/py/flwr/simulation/app.py
> +
Should this empty line be removed?

2022-04-04 17:10 UTC, danieljanes commented
Thanks for the PR @negedng, looks good! I've just added two small comments.

@tanertopal I agree, let's merge this :)

2022-04-05 09:57 UTC, tanertopal commented
@negedng do you want to apply Daniels suggestions or shall I do? Afterwards we can merge it.

2022-04-05 13:47 UTC, negedng commented
Also, a test shows that there is a sorting issue in the imports for simulation/app.py, but I can't figure out the proper way to sort the imports. Can you have a look? thanks!

2022-04-05 15:10 UTC, tanertopal commented on src/py/flwr/simulation/app.py
> +    initialized_server, initialized_config = _init_defaults(None, config, strategy, client_manager)
```suggestion
    initialized_server, initialized_config = _init_defaults(
        None, config, strategy, client_manager
    )
```

2022-04-11 09:08 UTC, negedng commented
Hi, any update on this? Do I need to change something?

2022-04-11 11:36 UTC, tanertopal commented
@negedng There was an issue with PyPi at the time I wanted to merge it and CI got blocked iirc. I'll have a look today again and merge it if the CI goes through.

2022-04-11 11:36 UTC, tanertopal approved these changes

2022-04-11 12:32 UTC, tanertopal commented
@negedng there is still an issue in:

```src/py/flwr/server/app.py:97: error: Missing positional argument "client_manager" in call to "_init_defaults"```

could you have a look?

2022-04-12 10:57 UTC, tanertopal approved these changes

2022-04-12 10:58 UTC, tanertopal requested changes

2022-04-12 10:58 UTC, tanertopal commented on src/py/flwr/server/app.py
> +            If no implementation is provided, then `start_simulation` will use
```suggestion
            If no implementation is provided, then `start_server` will use
```

2022-04-12 11:02 UTC, tanertopal submitted a review, later dismissed

2022-04-13 07:40 UTC, tanertopal commented on src/py/flwr/server/app.py
> +    initialized_server, initialized_config = _init_defaults(server, config, strategy, client_manager)
```suggestion
    initialized_server, initialized_config = _init_defaults(
        server, config, strategy, client_manager
    )
```

2022-04-13 08:45 UTC, tanertopal approved these changes

2022-04-13 10:10 UTC, merged