Create saving-and-loading-Pytorch-checkpoints.rst
adap/flower pull request #1364
Opened 2022-08-09 08:25 UTC by Linardos

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.

A minimal example for storing a PyTorch checkpoint. Several extra steps are added compared to the original saving progress example. Furthermore a way to load the latest checkpoint is added as well.

#### Any other comments?
This was developed with Daniel's help. We thought it was a resolved issue but apparently when loading the checkpoint, performance drops. It's as if training from scratch. We need to debug this further.

2022-08-31 16:28 UTC, danieljanes requested changes
Thanks for the PR @Linardos ! Looks good overall, I've added a few small suggestions. Could you re-compile the docs and check if everything looks good?

2022-08-31 16:28 UTC, danieljanes commented on doc/source/saving-and-loading-Pytorch-checkpoints.rst
> +        ) -> Optional[fl.common.Weights]:
```suggestion
        ) -> Tuple[Optional[Parameters], Dict[str, Scalar]]:
```

2022-08-31 16:28 UTC, danieljanes commented on doc/source/saving-and-loading-Pytorch-checkpoints.rst
> +            # log_dict['aggregated_parameters']=aggregated_parameters
```suggestion
```

2022-08-31 16:28 UTC, danieljanes commented on doc/source/saving-and-loading-Pytorch-checkpoints.rst
> +                # Save the model
```suggestion

                # Save the model
```

2022-08-31 16:28 UTC, danieljanes commented on doc/source/saving-and-loading-Pytorch-checkpoints.rst
> +.. code-block:: python
```suggestion

.. code-block:: python

```

2022-08-31 16:32 UTC, Linardos commented
Changes committed! I look forward to your thoughts after running the code. I hope we can resolve the issue.

2022-08-31 17:28 UTC, danieljanes commented
@Linardos, lightning fast! Did you have a chance to build the docs and check if the formatting looks good?

2022-09-06 08:43 UTC, danieljanes approved these changes

2022-09-06 08:43 UTC, merged