Flower Baseline: FedAvg MNIST
adap/flower pull request #1497
Opened 2022-12-02 14:43 UTC by charlesbvll

#### What does this implement/fix? Explain your changes.

Adds a new baseline for MNIST using a CNN in a federated setting.

2022-12-02 16:30 UTC, danieljanes requested changes

2022-12-02 16:30 UTC, danieljanes commented on baselines/flwr_baselines/publications/fedavg_mnist/README.md
> +The dataset used will be the one provided by torchvision.datasets.MNIST
```suggestion
The dataset used will be the one provided by `torchvision.datasets.MNIST`.
```

2022-12-02 16:30 UTC, danieljanes commented on baselines/flwr_baselines/publications/fedavg_mnist/README.md
> +In the paper, the number of clients used is 100. For the moment, 10 clients will be used in order to speed up the tests.
```suggestion
In the paper, the number of clients used is 100.
```

2022-12-02 16:30 UTC, danieljanes commented on baselines/flwr_baselines/publications/fedavg_mnist/README.md
> +The hyperparameters used will be the following :
```suggestion
The hyperparameters used will be the following:
```

2022-12-02 16:30 UTC, danieljanes commented on baselines/flwr_baselines/publications/fedavg_mnist/README.md
> +* The fraction of available clients for training (fraction_fit) will probably be varied between 0.1 and 1.
```suggestion
* The fraction of available clients for training (`fraction_fit`) will probably be varied between 0.1 and 1.
```

2022-12-02 16:30 UTC, danieljanes commented on baselines/flwr_baselines/publications/fedavg_mnist/README.md
> +* For evaluation, the fraction of available clients (fraction_evaluate) will be arbitrarily set to 0.5 (same as the Flower tutorial).
```suggestion
* For evaluation, the fraction of available clients (`fraction_evaluate`) will be arbitrarily set to 0.5 (same as the Flower tutorial).
```

2022-12-02 16:30 UTC, danieljanes commented on baselines/flwr_baselines/publications/fedavg_mnist/README.md
> +To mimic the paper, fl.server.strategy.FedAvg will be used.
```suggestion
To mimic the paper, `fl.server.strategy.FedAvg` will be used.
```

2022-12-06 08:45 UTC, charlesbvll commented
@danieljanes What I've already tried and tested for the mypy error :
(note that everything is working with Python, the error only pops up with mypy)

- After `import dataset`, `dir(dataset)` contains `load_datasets`, as expected, but mypy doesn't seem to recognize it
- Replacing `import dataset` and `dataset.load_datasets` by `from dataset import load_datasets`
- Replacing `import dataset` by `import dataset as dataset` or replacing `from dataset import load_datasets` by `from dataset import load_datasets as load_datasets`
- Playing around with the `__init__.py` even though all the files are in the same directory, this could be where I could have missed something

2022-12-06 10:20 UTC, charlesbvll commented
> @danieljanes What I've already tried and tested for the mypy error : (note that everything is working with Python, the error only pops up with mypy)
> 
> * After `import dataset`, `dir(dataset)` contains `load_datasets`, as expected, but mypy doesn't seem to recognize it
> * Replacing `import dataset` and `dataset.load_datasets` by `from dataset import load_datasets`
> * Replacing `import dataset` by `import dataset as dataset` or replacing `from dataset import load_datasets` by `from dataset import load_datasets as load_datasets`
> * Playing around with the `__init__.py` even though all the files are in the same directory, this could be where I could have missed something

I just changed the name of the `dataset.py` file and it worked, mypy probably had some collision issue with the `dataset` name.

2022-12-08 18:09 UTC, danieljanes requested changes
Looks good overall, I left a few comments on some details. In addition to that:
1. Remove the `.5` from the distributed validation plot
2. Add two empty lines after each module docstring (before the imports) 
3. Add tests, esp. for model and dataset

2022-12-08 18:09 UTC, danieljanes commented on baselines/flwr_baselines/publications/fedavg_mnist/README.md
> +**[Link to paper.](https://arxiv.org/pdf/1602.05629.pdf)**
Link to the abstract instead of the PDF

2022-12-08 18:09 UTC, danieljanes commented on baselines/flwr_baselines/publications/fedavg_mnist/README.md
> +The following baseline replicates the experiments in *Communication-Efficient Learning of Deep Networks from Decentralized Data*, which was the first paper to propose a federated approach to machine
Add authors/year after the paper title

2022-12-08 18:09 UTC, danieljanes commented on baselines/flwr_baselines/publications/fedavg_mnist/README.md
> +The following baseline replicates the experiments in *Communication-Efficient Learning of Deep Networks from Decentralized Data*, which was the first paper to propose a federated approach to machine
& rephrase the *first* paper comment

2022-12-08 18:09 UTC, danieljanes commented on baselines/flwr_baselines/publications/fedavg_mnist/utils.py
> +_test_cnn_size_mnist()
Is the utils scrips supposed to be used as a command line tool?
- Yes: let's document it in the README and move the function call underneath the usual `if __name__ == "__main__":
- No: remove the function call

2022-12-08 18:09 UTC, danieljanes commented on baselines/flwr_baselines/publications/fedavg_mnist/utils.py
> +def _test_cnn_size_mnist() -> None:
Move the test to a new test module named `model_test.py` (similar to how we do it in `src/py/flwr`)

2022-12-08 18:09 UTC, danieljanes commented on baselines/flwr_baselines/publications/fedavg_mnist/main.py
> +        An omegacong object that stores the hydra config.
```suggestion
        An omegaconf object that stores the hydra config.
```

2023-01-09 23:01 UTC, danieljanes approved these changes

2023-01-09 23:01 UTC, merged