Add FedProx+MNIST baseline
adap/flower pull request #1513
Opened 2022-12-16 12:56 UTC by charlesbvll

#### What does this implement/fix? Explain your changes.

Adds a new baseline for FedProx+MNIST, it is a Flower implementation of this [paper](https://arxiv.org/abs/1812.06127).

2023-02-16 06:58 UTC, danieljanes requested changes
Looks good overall, I added some small comments

2023-02-16 06:58 UTC, danieljanes commented on doc/source/changelog.md
> +- **Introduce new Flower Baseline: FedProx MNIST** ([#1513](https://github.com/adap/flower/pull/1513))
Move this up to a new "Unreleased" section

2023-02-16 06:58 UTC, danieljanes commented on baselines/flwr_baselines/publications/fedprox_mnist/tests.py
> +"""Used to test the model and the data partitionning."""
The entire module `tests.py` should be renamed to belong to one of the other modules, for example, `model_test.py`. If functions from multiple modules are being tested (e.g., `model` and `dataset`), then we should split this up into multiple test modules, each belonging to one of the existing non-test modules

2023-02-16 06:58 UTC, danieljanes commented on baselines/flwr_baselines/publications/fedprox_mnist/model.py
> +    paper :
Split this onto two separate lines (with an empty line in between - the first sentence in a docstring should not overflow to the next line).

2023-02-16 16:05 UTC, danieljanes approved these changes

2023-02-16 16:05 UTC, merged

2023-06-12 15:39 UTC, jafermarq commented
This baseline needs to be revisited:
* It should use 1000 clients (instead of 100)
* Different hyperparameters compared to paper? (see Appendix C2: https://arxiv.org/pdf/1812.06127.pdf) . It should use 10 clients per round (instead of full participation. currently is `fraction_fit`=1.0); Default learning rate should be changed to 0.3