Android example versions compatibility
adap/flower pull request #1603
Opened 2023-01-22 22:32 UTC by charlesbvll

## What does this implement/fix? Explain your changes.

Makes this example compatible with the versions `>=1.0.0` of `flwr`.

The code of the android app needs an update also, as currently there is the following issue: https://github.com/adap/flower/issues/1388

2023-01-22 22:55 UTC, charlesbvll commented
The proto file update is a possible fix but testing still needs to be done.

2023-01-23 20:24 UTC, danieljanes requested changes
Looks good overall, just two small comments!

2023-01-23 20:24 UTC, danieljanes commented on examples/android/client/app/src/main/java/flwr/android_client/MainActivity.java
> +//        @Override
Remove this commented-our line?

2023-01-23 20:24 UTC, danieljanes commented on examples/android/client/app/src/main/java/flwr/android_client/MainActivity.java
> +    public void runGRPC(View view){
We usually put just the first letter in caps (as in `GrpcRunnable`):
```suggestion
    public void runGrpc(View view){
```

2023-01-23 23:48 UTC, danieljanes approved these changes
Lgtm, great to have this updated to 1.0+!

2023-01-23 23:48 UTC, merged