Add custom strategy
adap/flower pull request #1623
Opened 2023-02-02 16:47 UTC by adam-narozniak

Add custom strategy creation in jupyter tutorial

2023-02-03 06:42 UTC, danieljanes commented
Is there a way to get a smaller diff?

2023-02-03 13:56 UTC, adam-narozniak commented
Yes, sorry. My IDE automatically changed the indentations between the time I copied the version from google colab.

2023-02-05 19:27 UTC, danieljanes requested changes

2023-02-05 19:27 UTC, danieljanes commented on doc/source/tutorial/Flower-3-Building-a-Strategy-PyTorch.ipynb
> +        "Let’s overwrite the configure_fit method such that it passes a higher learning rate (potentially also other hyperparameters to an optimizer) to a fraction of the client. We will keep the sam
```suggestion
        "Let’s overwrite the `configure_fit` method such that it passes a higher learning rate (potentially also other hyperparameters) to the optimizer of a fraction of the clients. We will keep the sampling of the clients as it is in `FedAvg` and then change the configuration dictionary (one of the `FitIns` attributes)."
```

2023-02-05 19:27 UTC, danieljanes commented on doc/source/tutorial/Flower-3-Building-a-Strategy-PyTorch.ipynb
> +        "In this notebook, we’ve seen how to implement a custom strategy. It allows very flexible client creation, fitting, and evaluation. You have to overwrite the abstract methods of the Strategy
```suggestion
        "In this notebook, we’ve seen how to implement a custom strategy. A custom strategy enables granular control over client node configuration, result aggregation, and more. To define a custom strategy, you only have to overwrite the abstract methods of the (abstract) base class `Strategy`. To make custom strategies even more powerful, you can pass custom functions to the constructor of your new class (`__init__`) and then call these functions whenever needed. "
```

2023-02-05 19:27 UTC, danieljanes commented on doc/source/tutorial/Flower-3-Building-a-Strategy-PyTorch.ipynb
> +        "        clients.\"\"\"\n",
```suggestion
        "        \"\"\"Return sample size and required number of clients.\"\"\"\n",
```

2023-02-05 19:28 UTC, danieljanes approved these changes
Lgtm!

2023-02-05 20:11 UTC, merged