Federated XGBoost horizontal quickstart
adap/flower pull request #1694
Opened 2023-02-24 15:55 UTC by dannymcy

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.

#### Any other comments?

2023-02-28 19:20 UTC, charlesbvll requested changes
I have only added one small comment about the location of a file but other than that there still is the question of the `xgboost` dependency. There is no perfect way to do it, but you probably want to add it to the global `pyproject.toml` under the extra dependencies, in a similar fashion to `ray`.

2023-02-28 19:20 UTC, charlesbvll commented on src/py/flwr/common/fedxgb.py
> +# Copyright 2020 Adap GmbH. All Rights Reserved.
This file should sit in `src/py/flwr/server/strategy` rather than `common`. `common` is for functions used both by `server` and `client`.

2023-03-14 14:24 UTC, danieljanes approved these changes

2023-03-15 07:44 UTC, charlesbvll approved these changes

2023-03-15 07:55 UTC, merged