Add Swift SDK API reference and structuring it
adap/flower pull request #1943
Opened 2023-06-19 06:51 UTC by danielnugraha

## Issue

### Description

There is no API reference for the Swift SDK, user have no way of looking up what the API of the Swift SDK looks like. Also there is lack of code documentation in the Swift SDK.

## Proposal

### Explanation

1. Add code documentation in the Swift SDK based on the current existing documentation in Python.
2. Structuring the documentation inside the API reference as follows:

- flwr
   - Client
   - GRPC
      - Messages
   - CoreML Client
      - Data Loader
      - Layer Wrapper
      - Model Parameters

### Checklist

- [x] Implement proposed change
- [ ] Discuss the API reference structure

2023-06-27 18:37 UTC, tanertopal commented on src/swift/flwr/Sources/Flower/Client/Client.swift
> +    /// Return set of client’s properties.
```suggestion
    /// Return set of client properties.
```

2023-06-27 18:39 UTC, tanertopal commented on src/swift/flwr/Sources/Flower/CoreML/MLFlwrClientModel.swift
> +/// A class that is responsible for loading and retrieving model parameters to and from CoreML model.
```suggestion
/// A class responsible for loading and retrieving model parameters to and from the CoreML model.
```

2023-06-27 18:48 UTC, danieljanes commented on src/swift/flwr/Sources/Flower/Client/Client.swift
> +/// - ``getParameters()``
Doesn't this also take `ins`?

2023-06-27 18:56 UTC, danieljanes requested changes

2023-06-27 18:56 UTC, danieljanes commented on src/swift/flwr/Sources/Flower/Client/Client.swift
>      func getParameters() -> GetParametersRes
```suggestion
    func getParameters(ins: GetParametersIns) -> GetParametersRes
```

2023-06-27 18:56 UTC, danieljanes commented on src/swift/flwr/Sources/Flower/Common/Typing.swift
> +/// Parameters request for a client
This is not a request:
```suggestion
/// Parameters message.
```

2023-06-27 18:56 UTC, danieljanes commented on src/swift/flwr/Sources/Flower/CoreML/MLFlwrClient.swift
> +/// - ``getParameters()``
```suggestion
/// - ``getParameters(ins:)``
```

2023-06-27 18:56 UTC, danieljanes commented on src/swift/flwr/Sources/Flower/CoreML/MLFlwrClient.swift
>      public func getParameters() -> GetParametersRes {
```suggestion
    public func getParameters(ins: GetParametersIns) -> GetParametersRes {
```

2023-06-28 08:03 UTC, danielnugraha commented on src/swift/flwr/Sources/Flower/CoreML/MLFlwrClient.swift
> +/// - ``getParameters()``
Will be implemented in a new PR.

2023-06-28 08:04 UTC, danielnugraha commented on src/swift/flwr/Sources/Flower/CoreML/MLFlwrClient.swift
>      public func getParameters() -> GetParametersRes {
Will be implemented in a new PR.

2023-06-28 08:04 UTC, danielnugraha commented on src/swift/flwr/Sources/Flower/Client/Client.swift
>      func getParameters() -> GetParametersRes
Will be implemented in a new PR.

2023-06-28 08:04 UTC, danielnugraha commented on src/swift/flwr/Sources/Flower/Client/Client.swift
> +/// - ``getParameters()``
Will be implemented in a new PR.

2023-06-28 08:23 UTC, tanertopal approved these changes

2023-06-28 08:23 UTC, merged