Update mxnet deps versions
adap/flower pull request #1982
Opened 2023-06-30 11:53 UTC by danielnugraha

## Issue

### Description

There are some inconsistencies with the examples that uses mxnet as its dependencies, resulting in error when poetry tries to resolve the dependencies. Using mxnet with version 1.7.1 results in error.

### Related issues/PRs

See also #1980 and #1981.

## Proposal

### Explanation

Following changes in pyproject.toml and requirements.txt are made to the examples that uses mxnet as its dependencies:
1. Fix mxnet version to 1.6.0
2. Fix python version to >=3.8, <3.11.
3. ^ on other dependencies are removed.
4. Flwr local dependency path is changed to the latest flwr-nightly version.
5. Flwr version is fixed to >=1.0, <2.0.

### Checklist

- [ ] Implement proposed change
- [ ] Make CI checks pass

### Any other comments?

2023-06-30 13:35 UTC, danieljanes requested changes

2023-06-30 13:35 UTC, danieljanes commented on examples/quickstart_mxnet/pyproject.toml
> +mxnet = "1.6.0"
Always add a newline at the end of the file

2023-07-04 08:50 UTC, tanertopal commented on examples/quickstart_mxnet/requirements.txt
> +flwr==0.17.0
I just merged `main` and resolved a conflict, and now I am confused. Is this correct @danielnugraha ?

2023-07-04 13:04 UTC, tanertopal approved these changes

2023-07-04 14:37 UTC, tanertopal approved these changes

2023-07-04 14:44 UTC, merged