Update serde.py and validator.py for Secure Aggregation
adap/flower pull request #2008
Opened 2023-07-05 20:15 UTC by panh99

## Issue

### Description

### Related issues/PRs

## Proposal

### Explanation

### Checklist

- [ ] Implement proposed change
- [ ] Write tests
- [ ] Update [documentation](https://flower.dev/docs/writing-documentation.html)
- [ ] Update [changelog](https://github.com/adap/flower/blob/main/doc/source/changelog.rst)
- [ ] Make CI checks pass
- [ ] Ping maintainers on [Slack](https://flower.dev/join-slack/) (channel `#contributions`)

### Any other comments?

2023-07-19 09:52 UTC, tanertopal reviewed
@panh99  I am less familiar with this part of Flower then @danieljanes  is. It looks good, but I'd wait for his review before merging.

2023-07-19 20:30 UTC, danieljanes requested changes
Let's move the changes in `flwr.common` into a new PR and focus this one to first merge the changes in `validator.py`. In addition to the review comments, it would be good to add unit tests to cover the changes.

2023-07-19 20:30 UTC, danieljanes commented on src/py/flwr/server/utils/validator.py
> +# pylint: disable-next=too-many-statements
This should work too:
```suggestion
# pylint: disable-next=too-many-branches,too-many-statements
```

2023-07-19 20:30 UTC, danieljanes commented on src/py/flwr/server/utils/validator.py
> +            err_msg = ", ".join([f"`{o}`" for o in has_fields])
```suggestion
            err_msg = ", ".join([f"`{field}`" for field in has_fields])
```

2023-07-19 20:30 UTC, danieljanes commented on src/py/flwr/server/utils/validator.py
> +        if sum(has_fields.values()) == 0:
Let's make this more boring:
```suggestion
        if not (has_fields["sa"] or has_fields["legacy_server_message"]):
```

2023-07-20 12:04 UTC, danieljanes requested changes

2023-07-20 12:04 UTC, danieljanes commented on src/py/flwr/common/serde.py
> +def __check_value(value: typing.Value) -> None:
```suggestion
def _check_value(value: typing.Value) -> None:
```

2023-07-20 12:04 UTC, danieljanes commented on src/py/flwr/common/serde.py
> +                f"(expect {data_type}, but get {type(element)})"
```suggestion
                f"(expected {data_type}, but got {type(element)})"
```

2023-07-20 16:03 UTC, danieljanes approved these changes

2023-07-20 16:03 UTC, merged