Fix missing square in proximal term of FedProx baseline
adap/flower pull request #2210
Opened 2023-08-11 08:16 UTC by charlesbvll

## Issue

### Description

The original FedProx paper describes the proximal term as $\frac{\mu}{2} || \omega - \omega_t ||^2$, but the current implementation sets it as $\frac{\mu}{2} || \omega_ - \omega_{t} ||$.

### Related issues/PRs

N/A

## Proposal

### Explanation

Add `torch.square` to the proximal term.

### Checklist

- [x] Implement proposed change
- [x] Make CI checks pass
- [ ] Ping maintainers on [Slack](https://flower.dev/join-slack/) (channel `#contributions`)

### Any other comments?

N/A

2023-08-16 16:00 UTC, jafermarq commented
I've re-run the experiments. I'll update the figure shown at the bottom of the readme

2023-08-31 17:29 UTC, danieljanes requested changes
Let's rename `Viz_and_plot_results.ipynb` to use all lowercase characters

2023-09-13 21:44 UTC, jafermarq approved these changes
cool

2023-09-19 17:47 UTC, danieljanes approved these changes

2023-09-19 17:47 UTC, merged