Add sphinx-intl to pyproject
adap/flower pull request #2267
Opened 2023-08-30 23:03 UTC by jafermarq

We need `sphinx-intl` to prepare docs translations. Maybe it got discarded unintentionally from https://github.com/adap/flower/pull/2201

2023-08-30 23:04 UTC, jafermarq commented
We might want to move that `sphinx-intl` package somewhere in the toml?

2023-08-31 07:15 UTC, danieljanes requested changes

2023-08-31 07:15 UTC, danieljanes commented on pyproject.toml
> +sphinx-intl = "2.1.0"
This needs to go to the dev dependencies

2023-08-31 07:37 UTC, charlesbvll approved these changes

2023-08-31 17:31 UTC, danieljanes approved these changes

2023-08-31 17:40 UTC, merged