Implement a RESTful API for Flower that supports creating and deleting nodes.
adap/flower pull request #2283
Opened 2023-09-04 04:19 UTC by cnxdeveloper

## Issue
By default, in restful API mode, Flower only supports clients running as anonymous. This makes it difficult to manage tasks and results for each client.
### Description

### Related issues/PRs

## Proposal
-  Update the 2 POST API requests to create and delete a node.
- Update the client code to support calling the API to create a node and delete a node.
- Update the code and README in ```flower/examples/mt-pytorch``` to run and test with restful mode.
### Explanation

### Checklist

- [ ] Implement proposed change
- [ ] Write tests
- [ ] Update [documentation](https://flower.dev/docs/writing-documentation.html)
- [ ] Update [changelog](https://github.com/adap/flower/blob/main/doc/source/changelog.rst)
- [ ] Make CI checks pass
- [ ] Ping maintainers on [Slack](https://flower.dev/join-slack/) (channel `#contributions`)

### Any other comments?

2023-09-05 14:00 UTC, cnxdeveloper commented
> Thanks for the well-scoped PR @cnxdeveloper! It looks pretty clean and easy to review, I will try to do a full review by the end of this week. In the meantime, could you already add an entry to the changelog in the `Unreleased` section?

Hi @danieljanes,
I really like the Flower framework. It's easy to use and scale up. Thank you for creating such an awesome repo!
I haven't updated the changelog in the ```Unreleased``` section yet. I'll do that later today.

2023-09-07 14:59 UTC, danieljanes requested changes
The PR is in a good shape 👍 I added some comments to align the coding style with the rest of the codebase

2023-09-07 14:59 UTC, danieljanes commented on examples/mt-pytorch/client.py
> +    )
`rest=True` is deprecated and will be removed. How about just adding comments to make it easier to switch between gRPC-rere and REST?
```suggestion
    fl.client.start_numpy_client(
        server_address="0.0.0.0:9092",  # "0.0.0.0:9093" for REST
        client=FlowerClient(),
        transport="grpc-rere",  # "rest" for REST
    )
```

2023-09-07 14:59 UTC, danieljanes commented on doc/source/ref-changelog.md
> +-  **Update REST API to support create and delete nodes** ([#2283](https://github.com/adap/flower/pull/2283))
```suggestion

-  **Update REST API to support create and delete nodes** ([#2283](https://github.com/adap/flower/pull/2283))

```

2023-09-07 14:59 UTC, danieljanes commented on examples/mt-pytorch/README.md
> +## Run Restful API mode
```suggestion
## Run with Driver API (REST transport layer)
```

2023-09-07 14:59 UTC, danieljanes commented on examples/mt-pytorch/README.md
> +Terminal 1: start Flower server restful mode
```suggestion
Terminal 1: start Flower server and enable REST transport layer
```

2023-09-07 14:59 UTC, danieljanes commented on examples/mt-pytorch/README.md
> +Terminal 2: start driver
```suggestion
Terminal 2: start Driver script
```

2023-09-07 14:59 UTC, danieljanes commented on examples/mt-pytorch/README.md
> +python driver
```suggestion
python driver.py
```

2023-09-07 14:59 UTC, danieljanes commented on examples/mt-pytorch/README.md
> +Open file ```client.py``` set variable ```restful_mode``` is ```True```
```suggestion
Open file `client.py` adjust `server_address` and `transport`.
```

2023-09-07 14:59 UTC, danieljanes commented on src/py/flwr/client/rest_client/connection.py
> +    def delete_node() -> bool:
Missing docstring

2023-09-07 14:59 UTC, danieljanes commented on src/py/flwr/server/fleet/rest_rere/rest_api.py
> +    # Return Serialize Protobuf
```suggestion

    # Return serialized ProtoBuf
```

2023-09-07 14:59 UTC, danieljanes commented on src/py/flwr/server/fleet/rest_rere/rest_api.py
> +    # Deserialize ProtoBuf
```suggestion

    # Deserialize ProtoBuf
```

2023-09-07 14:59 UTC, danieljanes commented on src/py/flwr/server/fleet/rest_rere/rest_api.py
> +    # Return serialized ProtoBuf
```suggestion

    # Return serialized ProtoBuf
```

2023-09-07 14:59 UTC, danieljanes commented on src/py/flwr/server/fleet/rest_rere/rest_api.py
> +    # Deserialize ProtoBuf
```suggestion

    # Deserialize ProtoBuf
```

2023-09-07 14:59 UTC, danieljanes commented on src/py/flwr/server/fleet/rest_rere/rest_api.py
> +    # parse base 64 to string
```suggestion
    # Parse base 64 to string
```

2023-09-07 14:59 UTC, danieljanes commented on src/py/flwr/client/rest_client/connection.py
> +        # get Node
```suggestion
        # Get Node
```

2023-09-07 14:59 UTC, danieljanes commented on src/py/flwr/client/rest_client/connection.py
> +        pull_task_ins_req_proto = PullTaskInsRequest( node=node)
```suggestion
        pull_task_ins_req_proto = PullTaskInsRequest(node=node)
```

2023-09-07 16:21 UTC, cnxdeveloper commented on src/py/flwr/client/rest_client/connection.py
> +    def delete_node() -> bool:
I have already updated

2023-09-08 09:12 UTC, danieljanes requested changes
Thanks for the fast updates, @cnxdeveloper! I added a few comments to improve consistency and I think that we can merge the PR once they are resolved.

2023-09-08 09:12 UTC, danieljanes commented on src/py/flwr/client/rest_client/connection.py
> +        pull_task_ins_req_proto = PullTaskInsRequest(node=node)
```suggestion
        # Request instructions (task) from server
        pull_task_ins_req_proto = PullTaskInsRequest(node=node)
```

2023-09-08 09:12 UTC, danieljanes commented on src/py/flwr/server/fleet/rest_rere/rest_api.py
> +    # Parse base 64 to string
```suggestion
    # Get the request body as raw bytes
```

2023-09-08 09:12 UTC, danieljanes commented on src/py/flwr/server/fleet/rest_rere/rest_api.py
> +    )
```suggestion
    create_node_response_proto = message_handler.create_node(
        request=create_node_request_proto,
        state=state
    )

    # Return serialized ProtoBuf
    create_node_response_bytes = create_node_response_proto.SerializeToString()
    return Response(
        status_code=200,
        content=create_node_response_bytes,
        headers={"Content-Type": "application/protobuf"},
    )
```

2023-09-08 09:12 UTC, danieljanes commented on src/py/flwr/server/fleet/rest_rere/rest_api.py
> +    )
```suggestion
    # Handle message
    delete_node_response_proto = message_handler.delete_node(
        request=delete_node_request_proto,
        state=state
    )

    # Return serialized ProtoBuf
    delete_node_response_bytes = delete_node_response_proto.SerializeToString()
    return Response(
        status_code=200,
        content=delete_node_response_bytes,
        headers={"Content-Type": "application/protobuf"},
    )
```

2023-09-08 11:42 UTC, danieljanes commented
@cnxdeveloper there's a formatting error: https://github.com/adap/flower/actions/runs/6120808796/job/16614584948?pr=2283

This can be fixed by running `./dev/format.sh`

2023-09-09 03:36 UTC, cnxdeveloper commented
> @cnxdeveloper there's a formatting error: https://github.com/adap/flower/actions/runs/6120808796/job/16614584948?pr=2283
> 
> This can be fixed by running `./dev/format.sh`

Hi @danieljanes I fixed code format by script  `./dev/format.sh`

2023-09-10 11:42 UTC, danieljanes requested changes
This should resolve the CI error

2023-09-10 11:42 UTC, danieljanes commented on src/py/flwr/client/rest_client/connection.py
> +            return False
```suggestion
            return
```

2023-09-10 12:21 UTC, danieljanes requested changes

2023-09-10 12:21 UTC, danieljanes commented on src/py/flwr/client/rest_client/connection.py
> +            return None
```suggestion
            return
```

2023-09-10 12:21 UTC, danieljanes commented on src/py/flwr/client/rest_client/connection.py
> +        node_store[KEY_NODE] = create_node_response_proto.node
```suggestion
        node_store[KEY_NODE] = create_node_response_proto.node  # pylint: disable=no-member
```

2023-09-10 12:24 UTC, danieljanes commented
I fixed a few linter warnings, could you reformat once more @cnxdeveloper?

2023-09-10 17:44 UTC, danieljanes commented
Almost there! Only formatting issues in two markdown files left: https://github.com/adap/flower/actions/runs/6138546228/job/16655523326?pr=2283#step:6:252

2023-09-11 03:00 UTC, cnxdeveloper commented
> Almost there! Only formatting issues in two markdown files left: https://github.com/adap/flower/actions/runs/6138546228/job/16655523326?pr=2283#step:6:252

Hi I tried to use format script to reformat these markdown file

2023-09-11 07:38 UTC, danieljanes requested changes

2023-09-11 07:38 UTC, danieljanes commented on src/py/flwr/client/rest_client/connection.py
>          # Serialize ProtoBuf to bytes
```suggestion
```

2023-09-11 07:38 UTC, danieljanes commented on src/py/flwr/client/rest_client/connection.py
> +    # Enable create_node and delete_node to store node
```suggestion

    # Enable create_node and delete_node to store node
```

2023-09-11 07:49 UTC, danieljanes approved these changes
Lgtm, merging! Thanks for the contribution @cnxdeveloper 🎉

2023-09-11 07:50 UTC, merged