Docker server image docs
adap/flower pull request #2695
Opened 2023-12-07 18:14 UTC by Robert-Steiner

## Issue

### Description

### Related issues/PRs

## Proposal

### Explanation

### Checklist

- [ ] Implement proposed change
- [ ] Write tests
- [ ] Update [documentation](https://flower.dev/docs/writing-documentation.html)
- [ ] Update [changelog](https://github.com/adap/flower/blob/main/doc/source/changelog.rst)
- [ ] Make CI checks pass
- [ ] Ping maintainers on [Slack](https://flower.dev/join-slack/) (channel `#contributions`)

### Any other comments?

2023-12-08 16:33 UTC, Robert-Steiner commented
I just saw that we rename `certificates` to `credentials` in #2663. I can update it in my pr but the SSL example won't work for Flower 1.6.0 and below. What would be the best way to handle that? Maybe adding a note?

2023-12-17 14:39 UTC, danieljanes requested changes

2023-12-17 14:39 UTC, danieljanes commented on doc/source/how-to-run-flower-in-docker.rst
> +Run Flower in Docker
@Robert-Steiner please also rename the file to reflect this:
```suggestion
Run Flower using Docker
```

2023-12-17 14:39 UTC, danieljanes commented on doc/source/how-to-install-flower.rst
> +`How to run Flower in Docker <https://flower.dev/docs/framework/how-to-run-flower-in-docker.html>`_
```suggestion
`How to run Flower using Docker <https://flower.dev/docs/framework/how-to-run-flower-in-docker.html>`_
```

2023-12-17 14:39 UTC, danieljanes commented on doc/source/how-to-run-flower-in-docker.rst
> +the container after it exits.
```suggestion
uses Flower 1.6.0, Python 3.11 and Ubuntu 22.04. The ``--rm`` flag tells Docker to remove
the container after it exits.
```

2023-12-17 14:39 UTC, danieljanes commented on doc/source/how-to-run-flower-in-docker.rst
> +  By default, Flower uses a SQLite in-memory database to store its state. When using the Docker flag
```suggestion
  By default, the Flower server keeps state in-memory. When using the Docker flag
```

2023-12-17 14:39 UTC, danieljanes commented on doc/source/how-to-run-flower-in-docker.rst
> +  The ``--insecure`` flag enables insecure communication (not using HTTPS) and should only be used
```suggestion
  The ``--insecure`` flag enables insecure communication (using HTTP, not HTTPS) and should only be used
```

2023-12-17 14:39 UTC, danieljanes commented on doc/source/how-to-run-flower-in-docker.rst
> +  page contains a section that will guide you through the process.
Note that the bash script we provide is for testing purposes only:
```suggestion
.. note::

  For testing purposes, you can generate your own self-signed certificates. The
  `Enable SSL connections <https://flower.dev/docs/framework/how-to-enable-ssl-connections.html#certificates>`_
  page contains a section that will guide you through the process.
```

2023-12-18 10:08 UTC, Robert-Steiner commented
> I just saw that we rename `certificates` to `credentials` in #2663. I can update it in my pr but the SSL example won't work for Flower 1.6.0 and below. What would be the best way to handle that? Maybe adding a note?

@danieljanes One solution I can think of is to keep the "--certificates" parameter but mark it as deprecated to avoid a breaking change. wdyt?

2023-12-18 22:39 UTC, danieljanes commented
@Robert-Steiner `flower-server` is still marked "experimental", so we can still change things without deprecating them. This will change soon, but for now it's ok to just change it.

2023-12-19 12:41 UTC, Robert-Steiner commented
> @Robert-Steiner `flower-server` is still marked "experimental", so we can still change things without deprecating them. This will change soon, but for now it's ok to just change it.

Alright, that makes sense, then I'll leave it as it is.

2023-12-20 08:54 UTC, tanertopal approved these changes
lgtm!

2023-12-20 16:30 UTC, merged