Retire the example of quickstart-xgboost-horizontal
adap/flower pull request #2801
Opened 2024-01-16 10:45 UTC by yan-gao-GY

## Issue

### Description
We first thank the author of this example. As the implementation of this example has been combined with a Flower baseline, we decide to remove this example.

## Proposal
1. Remove the example of `quickstart-xgboost-horizontal`.
2. Move the related strategy `FedXgbNnAvg` to its baseline folder.

### Changelog entry

<general>

2024-01-17 14:00 UTC, danieljanes requested changes

2024-01-17 14:00 UTC, danieljanes commented on src/py/flwr/server/strategy/fedxgb_nn_avg.py
>      def __init__(self, *args: Any, **kwargs: Any) -> None:
Shoul we create sth like `flwr.common.logger.warn_experimental_feature` but for deprecated features and use it in the constructor here to print a warning message to users?

2024-01-17 20:23 UTC, danieljanes commented on src/py/flwr/server/strategy/fedxgb_nn_avg.py
> +        warn_deprecated_feature("`FedXgbNnAvg`")
```suggestion
        warn_deprecated_feature("`FedXgbNnAvg` strategy")
```

2024-01-17 20:24 UTC, danieljanes commented on src/py/flwr/server/strategy/fedxgb_nn_avg.py
> +    https://github.com/adap/flower/tree/main/baselines/hfedxgboost.
```suggestion
    Warning
    -------
    This strategy is deprecated, but a copy of it is available in Flower Baselines:
    https://github.com/adap/flower/tree/main/baselines/hfedxgboost.
```

2024-01-17 20:25 UTC, danieljanes approved these changes

2024-01-18 21:31 UTC, jafermarq approved these changes

2024-01-18 21:42 UTC, merged