Update xgboost-quickstart example for independent xgb object instantiation
adap/flower pull request #3426
Opened 2024-05-10 09:00 UTC by yan-gao-GY

## Issue

### Description
The xgboost-quickstart example instantiates xgb object at the first round and persist over FL rounds. This is ok for long-running clients in deployment mode within cross-silo settings. However, it is not feasible to use Flower Simulation and migrate to Flower Next.

## Proposal
Implement the same Xgb client as the comprehensive xgb example does, where the xgb object is instantiated independently every single round. No need to persist the xgb object over FL rounds.

### Changelog entry
<examples>

2024-05-17 13:25 UTC, chongshenng commented on examples/xgboost-quickstart/client.py
> +        # Bagging: extract the last N=num_local_round trees for sever aggregation
Small typo: sever > server

2024-05-17 13:29 UTC, chongshenng commented on examples/xgboost-quickstart/requirements.txt
I'd suggest removing `requirements.txt` and use only `pyproject.toml` for the installation.

2024-05-17 13:30 UTC, chongshenng commented on examples/xgboost-quickstart/pyproject.toml
I suggest using this `pyproject.toml` to install the dependencies for the project - it no longer depends on `poetry`:

```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "quickstart-xgboost"
version = "0.1.0"
description = "XGBoost Federated Learning Quickstart with Flower"
authors = [
    { name = "The Flower Authors", email = "hello@flower.ai" },
]
dependencies = [
    "flwr>=1.8.0,<2.0",
    "flwr-datasets>=0.1.0,<1.0.0",
    "xgboost>=2.0.0,<3.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]
```

2024-05-17 13:31 UTC, chongshenng commented on examples/xgboost-quickstart/pyproject.toml
I also bumped the minimum version of Flower to 1.8.

2024-05-17 13:34 UTC, chongshenng requested changes
Overall looks fine, thanks @yan-gao-GY. I think one more PR is needed to convert this fully to use `ClientApp` and `ServerApp`. (We should place `start_client` and `start_server` within a `if __name__ == "__main__"` for this). Let's draft another PR for this upgrade. 

You'll also need to update the PR title to conform to the new format. I think something like `fix(examples) Update XGBoost quickstart examples for independent object instantiation` could work.

2024-05-28 09:26 UTC, yan-gao-GY commented on examples/xgboost-quickstart/pyproject.toml
Ok! so we don't mention that `we recommend Poetry to install those dependencies` any more in readme right? Is this the thing we want to do for all examples? @jafermarq

2024-05-28 09:44 UTC, jafermarq commented on examples/xgboost-quickstart/pyproject.toml
yes, we are gradually removing the need for poetry in the examples. An examples of an updated example is [quickstart-pytorch](https://github.com/adap/flower/tree/main/examples/quickstart-pytorch#installing-dependencies).

2024-05-28 09:45 UTC, jafermarq commented
> @chongshenng Thanks a lot for your comments and suggestions!
> 
> Do we want to fully replace `start_client` and `start_server` now? I saw other examples keep both and using Flower Next with a `preview` label.

Let's do that later in a different PR.

2024-05-30 10:30 UTC, jafermarq approved these changes

2024-05-30 10:33 UTC, chongshenng approved these changes
lgtm!

2024-05-30 10:33 UTC, merged