docs(framework:skip) Add docs for distributed Docker Compose guide
adap/flower pull request #3928
Opened 2024-07-26 15:07 UTC by Robert-Steiner

## Issue

### Description

- Add docs for distributed Docker Compose guide.
- Depends on: #3916, #3924 

### Related issues/PRs

## Proposal

### Explanation

### Checklist

- [ ] Implement proposed change
- [ ] Write tests
- [ ] Update [documentation](https://flower.ai/docs/writing-documentation.html)
- [ ] Make CI checks pass
- [ ] Ping maintainers on [Slack](https://flower.ai/join-slack/) (channel `#contributions`)

### Any other comments?

2024-09-16 08:21 UTC, chongshenng requested changes
Thanks for the PR @Robert-Steiner! Overall looks good. I've left a few comments in the PR itself. 

Nits: 
* Can you use code-block for ``SuperExec`` throughout? 
* Can you format and lint the code with ``rstfmt``? We'll be using this in our CI in the coming days, so it'll be good to get it formatted as well.

2024-09-16 08:21 UTC, chongshenng commented on doc/source/docker/tutorial-deploy-on-multiple-machines.rst
> +- Docker Compose is installed on both your local machine and the remote machine.
```suggestion
- Docker Compose V2 is installed on both your local machine and the remote machine.
```

2024-09-16 08:21 UTC, chongshenng commented on doc/source/docker/tutorial-deploy-on-multiple-machines.rst
> +   Compose file. If you have certificates, you can continue with Step 2.
```suggestion
#. Use the ``certs.yml` Compose file to generate your own self-signed certificates.
   If you have certificates, you can continue with Step 2.
```

2024-09-16 08:21 UTC, chongshenng commented on doc/source/docker/tutorial-deploy-on-multiple-machines.rst
> +with Flower configured to use TLS encryption and persist SuperLink state across restarts.
```suggestion
with Flower configured to use TLS encryption and persist SuperLink state across restarts. A server consists of a SuperLink and ``SuperExec``. For more details
about the Flower architecture, refer to the :doc:Flower Architecture`../explanation-flower-architecture.rst` explainer page.
```

2024-09-16 08:21 UTC, chongshenng commented on doc/source/docker/tutorial-deploy-on-multiple-machines.rst
> +   $ docker compose -f server/compose.yml up --build -d
```suggestion
   $ ssh <your-remote-machine>
   # In your remote machine
   $ cd <path-to-``server``-directory>
   $ export PROJECT_DIR=../quickstart-sklearn-tabular
   $ docker compose -f server/compose.yml up --build -d
```

2024-09-16 08:21 UTC, chongshenng commented on doc/source/docker/tutorial-deploy-on-multiple-machines.rst
> +
```suggestion

   # In the `docker/distributed/client` directory
```

2024-09-16 08:21 UTC, chongshenng commented on doc/source/docker/tutorial-deploy-on-multiple-machines.rst
> +``pyproject.toml`` file:
```suggestion
``[tool.flwr.federations.remote-superexec]`` table in the ``pyproject.toml`` file. Here, we have named our remote federation ``remote-superexec``:
```

2024-09-24 07:10 UTC, chongshenng commented on doc/source/docker/tutorial-deploy-on-multiple-machines.rst
> +.. |quickstart_skearn_tabular| replace::
```suggestion
.. |quickstart_sklearn_tabular| replace::
```

2024-09-24 07:11 UTC, chongshenng commented on doc/source/docker/tutorial-deploy-on-multiple-machines.rst
> +.. _quickstart_skearn_tabular: https://github.com/adap/flower/tree/main/examples/quickstart-sklearn-tabular
```suggestion
.. _quickstart_sklearn_tabular: https://github.com/adap/flower/tree/main/examples/quickstart-sklearn-tabular
```

2024-09-24 08:07 UTC, chongshenng approved these changes
lgtm!

2024-09-24 10:41 UTC, tanertopal approved these changes
Lgtm!

2024-09-24 11:18 UTC, merged