feat(framework:skip) Update Docker Compose `complete` files for 1.13.0
adap/flower pull request #4413
Opened 2024-11-01 13:27 UTC by Robert-Steiner

## Issue

### Description

### Related issues/PRs

## Proposal

### Explanation

### Checklist

- [ ] Implement proposed change
- [ ] Write tests
- [ ] Update [documentation](https://flower.ai/docs/writing-documentation.html)
- [ ] Make CI checks pass
- [ ] Ping maintainers on [Slack](https://flower.ai/join-slack/) (channel `#contributions`)

### Any other comments?

2024-11-04 15:14 UTC, chongshenng commented on src/docker/complete/compose.yml
>      image: flwr/superlink:${FLWR_VERSION:-1.12.0}
```suggestion
    image: flwr/superlink:${FLWR_VERSION:-1.13.0}
```

2024-11-04 15:14 UTC, chongshenng commented on src/docker/complete/compose.yml
> +        FROM flwr/serverapp:${FLWR_VERSION:-1.12.0}
```suggestion
        FROM flwr/serverapp:${FLWR_VERSION:-1.13.0}
```

2024-11-04 15:41 UTC, chongshenng requested changes
@Robert-Steiner Thanks for this. I think the only the Docker image tags needs to be changed to `nightly` since it doesn't work with `1.12` right now.

2024-11-04 15:43 UTC, Robert-Steiner commented on src/docker/complete/compose.yml
>      image: flwr/superlink:${FLWR_VERSION:-1.12.0}
good point!

2024-11-04 15:53 UTC, Robert-Steiner commented
> @Robert-Steiner Thanks for this. I think the only the Docker image tags needs to be changed to `nightly` since it doesn't work with `1.12` right now.

I changed it to nightly, but we’ll need to update it to 1.13.0 before releasing 1.13.0, to make it part of the release tag. I used to change the version after the release, but this caused an issue with the link in the [Run Flower Quickstart Examples with Docker Compose](https://flower.ai/docs/framework/docker/run-quickstart-examples-docker-compose.html) doc, where the link points to the correct tag, but the default version is still set to the previous release:

```
curl https://raw.githubusercontent.com/adap/flower/refs/tags/v1.12.0/src/docker/complete/compose.yml \
    -o compose.yml
```

I’ve added a note in the release docs.

2024-11-05 08:22 UTC, chongshenng approved these changes
lgtm!

2024-11-05 08:22 UTC, chongshenng commented
> I changed it to nightly, but we’ll need to update it to 1.13.0 before releasing 1.13.0, to make it part of the release tag

@Robert-Steiner yes, makes sense!

2024-11-11 11:45 UTC, tanertopal approved these changes
lgtm!

2024-11-11 11:58 UTC, merged