feat(framework:skip) Update Docker Compose `distributed` files for 1.13.0
adap/flower pull request #4414
Opened 2024-11-01 13:30 UTC by Robert-Steiner

## Issue

### Description

Updates the Docker Compose complete setup to incorporate the upcoming 1.13.0 changes.

### Related issues/PRs

## Proposal

### Explanation

### Checklist

- [ ] Implement proposed change
- [ ] Write tests
- [ ] Update [documentation](https://flower.ai/docs/writing-documentation.html)
- [ ] Make CI checks pass
- [ ] Ping maintainers on [Slack](https://flower.ai/join-slack/) (channel `#contributions`)

### Any other comments?

2024-11-04 15:46 UTC, chongshenng requested changes
Thanks @Robert-Steiner. Similar to #4413, let's set the image tags to `nightly`.

2024-11-04 15:46 UTC, chongshenng commented on src/docker/distributed/server/compose.yml
>      image: flwr/superlink:${FLWR_VERSION:-1.12.0}
```suggestion
    image: flwr/superlink:${FLWR_VERSION:-1.12.0}
```
Same as [this comment](https://github.com/adap/flower/pull/4413#discussion_r1827899886). This should be `nightly` for now, until `1.13` is released.

2024-11-04 15:46 UTC, chongshenng commented on src/docker/distributed/server/compose.yml
> +        FROM flwr/serverapp:${FLWR_VERSION:-1.12.0}
Same comment as above.

2024-11-04 15:46 UTC, chongshenng commented on src/docker/distributed/server/compose.yml
> +        ENTRYPOINT ["flower-serverapp"]
```suggestion
        ENTRYPOINT ["flwr-serverapp"]
```

2024-11-05 08:24 UTC, chongshenng approved these changes
lgtm!

2024-11-11 11:43 UTC, tanertopal approved these changes
Lgtm!

2024-11-11 11:49 UTC, merged