docs(framework:skip) Update Docker Compose docs for 1.13.0
adap/flower pull request #4441
Opened 2024-11-06 17:41 UTC by Robert-Steiner

## Issue

### Description

### Related issues/PRs

## Proposal

### Explanation

### Checklist

- [ ] Implement proposed change
- [ ] Write tests
- [ ] Update [documentation](https://flower.ai/docs/writing-documentation.html)
- [ ] Make CI checks pass
- [ ] Ping maintainers on [Slack](https://flower.ai/join-slack/) (channel `#contributions`)

### Any other comments?

2024-11-11 15:08 UTC, chongshenng submitted a review, later dismissed
lgtm!

2024-11-18 19:49 UTC, chongshenng commented on doc/source/docker/tutorial-deploy-on-multiple-machines.rst
> +across restarts. A server consists of a SuperLink and ServerApp. For more details about
```suggestion
across restarts. A server consists of a SuperLink and a ``ServerApp``. For more details about
```

2024-11-18 19:52 UTC, chongshenng commented on doc/source/docker/tutorial-quickstart-docker-compose.rst
> +   allowing it to install dependencies in the ClientApp and ServerApp images correctly.
```suggestion
   allowing it to install dependencies in the ``flwr/serverapp` and ``flwr/clientapp`` images correctly.
```

2024-11-18 20:03 UTC, chongshenng commented on doc/source/docker/tutorial-quickstart-docker-compose.rst
> +   allowing it to install dependencies in the ClientApp and ServerApp images correctly.
```suggestion
   allowing it to install dependencies in the ServerApp and ClientApp images correctly.
```

2024-11-18 20:06 UTC, chongshenng commented on doc/source/docker/tutorial-quickstart-docker-compose.rst
> +             - flwr.superexec.deployment:executor
Let's remove these lines since it's `flwr.superexec.deployment:executor` by default.

2024-11-18 20:08 UTC, chongshenng requested changes
@Robert-Steiner thanks! Overall looks good, only minor comments.

2024-11-19 15:32 UTC, chongshenng approved these changes
LGTM!

2024-11-20 09:34 UTC, danieljanes commented on doc/source/docker/tutorial-deploy-on-multiple-machines.rst
> +across restarts. A server consists of a SuperLink and a ServerApp. For more details
```suggestion
across restarts. A server consists of a SuperLink and a ``ServerApp``. For more details
```

2024-11-20 09:48 UTC, danieljanes approved these changes

2024-11-20 10:12 UTC, merged