Testing | Init Checker
adap/flower pull request #582
Opened 2021-01-12 09:49 UTC by CanTuerk

This PR will implement a script which will search the specified directory ( `src/py` ) for missing `__init__.py` files. Refers to #581

2021-01-15 08:45 UTC, tanertopal requested changes

2021-01-15 08:45 UTC, tanertopal commented on src/py/flwr_tool/init_py_check.py
> +        check_missing_init_files(abs_path)
```suggestion
if __name__ == "__main__":
    if len(sys.argv) == 0:
        raise Exception("Please provide at least one directory path relative to your current working directory.")    
    for i in range(len(sys.argv)):
        abs_path: str = os.path.abspath(os.path.join(os.getcwd(), sys.argv[i]))
        check_missing_init_files(abs_path)
```

2021-01-18 09:17 UTC, tanertopal submitted a review, later dismissed

2021-01-18 10:13 UTC, danieljanes approved these changes

2021-01-18 15:56 UTC, tanertopal approved these changes

2021-01-18 16:16 UTC, danieljanes approved these changes

2021-01-18 16:37 UTC, merged