Create MXNet Example
adap/flower pull request #614
Opened 2021-02-01 18:33 UTC by mariaboerner1987

- create init
- create pyproject.toml
- create mxnet central
- create flower client
- create flower server

2021-03-06 17:22 UTC, tanertopal requested changes

2021-03-06 17:22 UTC, tanertopal commented on examples/mxnet_federated/server.py
> +
```suggestion
```

2021-03-06 17:22 UTC, tanertopal commented on examples/quickstart_mxnet/server.py
> +
Remove one new line
```suggestion
```

2021-03-06 23:19 UTC, danieljanes requested changes

2021-03-06 23:19 UTC, danieljanes commented on examples/quickstart_mxnet/README.md
> +This example demonstrates how to run a MXNEt machine learning project federated with Flower.
```suggestion
This example demonstrates how to run a MXNet machine learning project federated with Flower.
```

2021-03-06 23:19 UTC, danieljanes commented on examples/mxnet_federated/README.md
> +This example demonstrates how an already existing centralized MXNEt-based machine learning project can be federated with Flower.
```suggestion
This example demonstrates how an already existing centralized MXNet-based machine learning project can be federated with Flower.
```

2021-03-06 23:19 UTC, danieljanes commented on examples/mxnet_federated/README.md
> +This introductory example for Flower uses MXNet, but you're not required to be a MXNet expert to run the example. The example will help you to understand how Flower can be used to build federated lea
```suggestion
This introductory example for Flower uses MXNet, but you're not required to be a MXNet expert to run the example. The example will help you to understand how Flower can be used to build federated learning use cases based on an existing MXNet project.
```

2021-03-06 23:19 UTC, danieljanes commented on examples/mxnet_federated/README.md
> +# MXNet: Basic Example
Should we call this 
```suggestion
# MXNet: From Centralized To Federated
```
to be consistent with the PyTorch version?

2021-03-06 23:19 UTC, danieljanes commented on examples/mxnet_federated/README.md
> +# MXNet: Basic Example
Which means we should also rename the directory to `mxnet_from_centralized_to_federated`

2021-03-08 14:45 UTC, danieljanes requested changes

2021-03-08 14:45 UTC, danieljanes commented on examples/mxnet_from_centralized_to_federated/client.py
> +    """Load data, start CifarClient."""
Typo:
```suggestion
    """Load data, start MNISTClient."""
```

2021-03-08 14:45 UTC, danieljanes commented on examples/mxnet_from_centralized_to_federated/client.py
> +    # Setup context to GPU and if not available to CPU
```suggestion
    # Set context to GPU or - if not available - to CPU
```

2021-03-08 14:45 UTC, danieljanes commented on examples/mxnet_from_centralized_to_federated/client.py
> +    # Define model from centralized training
```suggestion
    # Load model (from centralized training)
```

2021-03-08 14:45 UTC, danieljanes commented on examples/mxnet_from_centralized_to_federated/client.py
> +        return float(loss), self.val_data.batch_size, {"accuracy":float(accuracy)}
```suggestion
        return float(loss), self.val_data.batch_size, {"accuracy": float(accuracy)}
```

2021-03-08 14:45 UTC, danieljanes commented on examples/mxnet_from_centralized_to_federated/client.py
> +        self, parameters: List[np.ndarray], config: Dict[str, str]
```suggestion
        self, parameters: List[np.ndarray], config: Dict
```

2021-03-08 14:45 UTC, danieljanes commented on examples/mxnet_from_centralized_to_federated/client.py
> +        self, parameters: List[np.ndarray], config: Dict[str, str]
```suggestion
        self, parameters: List[np.ndarray], config: Dict
```

2021-03-08 14:45 UTC, danieljanes commented on examples/mxnet_from_centralized_to_federated/client.py
> +    ) -> Tuple[List[np.ndarray], int]:
```suggestion
    ) -> Tuple[List[np.ndarray], int, Dict]:
```

2021-03-08 14:45 UTC, danieljanes commented on examples/mxnet_from_centralized_to_federated/client.py
> +    ) -> Tuple[int, float, float]:
```suggestion
    ) -> Tuple[int, float, Dict]:
```

2021-03-08 14:45 UTC, danieljanes commented on examples/mxnet_from_centralized_to_federated/client.py
> +    # Make one forward propagation to initialize parameters
```suggestion
    # Do one forward propagation to initialize parameters
```

2021-03-08 14:45 UTC, danieljanes commented on examples/mxnet_from_centralized_to_federated/mxnet_mnist.py
> +    # Setup context to GPU and if not available to CPU
```suggestion
    # Set context to GPU or - if not available - to CPU
```

2021-03-08 14:45 UTC, danieljanes commented on examples/quickstart_mxnet/README.md
> +# MXNet: Basic Example
```suggestion
# Flower Example using MXNet
```
(to be consistent with our other quickstart examples)

2021-03-10 17:41 UTC, tanertopal approved these changes

2021-03-10 17:42 UTC, danieljanes approved these changes

2021-03-10 17:42 UTC, merged