DPSGD Mnist Example
adap/flower pull request #736
Opened 2021-05-20 12:14 UTC by cozek

This PR adds an example where Flower is used to train a federeated learning system where clients are free to choose 
between non-private and private optimizers. Specifically, clients can choose to train Keras models using the standard SGD optimizer or __Differentially Private__ SGD (DPSGD) from [Tensorflow Privacy](https://github.com/tensorflow/privacy). For this task we use the MNIST dataset which is split artificially among clients. This causes the dataset to be i.i.d. The clients using DPSGD track the amount of privacy spent and display it at the end of the training. 

This example is adapted from https://github.com/tensorflow/privacy/blob/master/tutorials/mnist_dpsgd_tutorial_keras.py
In addition, i have used code in the examples/advanced_tensorflow and examples/simulation to build this example.

Due to lack of system resources, I am unable to run 10 clients at the same time and test like the other examples.
I have tested the scripts using 3 clients and they seem to work. Also, I am have used conda to manage the dependencies.

I would appreciate it if the reviewers would kindly test out the code.

2021-05-21 11:34 UTC, danieljanes requested changes
Thanks for the PR @cozek - it looks great!

I left comments on a few minor details, apart from that I'd say it's ready to be merged soon. Please also run the `black` formatter once (the CI doesn't check example formatting yet). If you've set the project up using Poetry, you can just run `poetry run ./dev/format.sh` from the project root.

2021-05-21 11:34 UTC, danieljanes commented on examples/dp-sgd-mnist/pyproject.toml
> +tensorflow-privacy = {git = "https://github.com/tensorflow/privacy"}
It's recommended to pin git dependencies to a specific commit (this avoids breaking changes from affecting our code example).

2021-05-21 11:34 UTC, danieljanes commented on examples/dp-sgd-mnist/common.py
> +    # # Delta is set to approximate 1 / (number of training points).
Duplicate `#`

2021-05-21 11:34 UTC, danieljanes commented on examples/dp-sgd-mnist/common.py
> +    X = np.array(X, dtype=np.float32) / 255
Docstring missing

2021-05-21 11:34 UTC, danieljanes commented on examples/dp-sgd-mnist/client.py
> +        print("Privacy Lost: ", PRIVACY_LOSS)
Should the log message change here?
```suggestion
        print("Privacy Loss: ", PRIVACY_LOSS)
```

2021-05-31 14:34 UTC, danieljanes requested changes
We ran the example with 10 clients and DPSGD enabled, they converge to ~89% test set accuracy.

There are a few more (minor) comments on the README, once they're resolved we can merge.

2021-05-31 14:34 UTC, danieljanes commented on examples/dp-sgd-mnist/README.md
> +poetry run python3 server.py --num-clients 3 --partition 0 --dpsgd True &
```suggestion
poetry run python3 client.py --num-clients 3 --partition 0 --dpsgd True &
```

2021-05-31 14:34 UTC, danieljanes commented on examples/dp-sgd-mnist/README.md
> +```shell
Please add a blank line before this line

2021-05-31 14:34 UTC, danieljanes commented on examples/dp-sgd-mnist/README.md
> +poetry run python3 client.py --partition 1 --local-epochs 4 --dpsgd True
Should we perhaps add `--num-clients 3` here as well?

2021-06-01 03:21 UTC, cozek commented
@danieljanes Thanks for testing it out. Maybe we can add a line at the end about the expected accuracy based on your testing with 10 clients.
```
Running this example with 10 clients and DPSGD enabled keeping all other parameters at their default,
should converge to ~89% test set accuracy.
```

2021-06-02 11:11 UTC, danieljanes submitted a review, later dismissed
@cozek PR looks good now! Do you want to add the accuracy comment? We can merge either way

2021-06-02 16:56 UTC, cozek commented
@danieljanes I have added the comment regarding test results. I am happy with it now and its good to merge.

2021-06-02 19:36 UTC, danieljanes approved these changes

2021-06-02 19:37 UTC, merged